package pojo;
// Generated Dec 12, 2017 12:31:54 AM by Hibernate Tools 4.3.1



/**
 * Mhs generated by hbm2java
 */
public class Mhs  implements java.io.Serializable {


     private String stb;
     private String nama;
     private String ket;
     private String alamat;

    public Mhs() {
    }

    public Mhs(String stb, String nama, String ket, String alamat) {
       this.stb = stb;
       this.nama = nama;
       this.ket = ket;
       this.alamat = alamat;
    }
   
    public String getStb() {
        return this.stb;
    }
    
    public void setStb(String stb) {
        this.stb = stb;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKet() {
        return this.ket;
    }
    
    public void setKet(String ket) {
        this.ket = ket;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


